apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/prune: Disabled
    kustomize.toolkit.fluxcd.io/ssa: Ignore
spec:
  interval: 10m0s
  path: my-app-repo/clusters/my-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-apps